# Generated by Django 4.2.23 on 2026-03-03 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleaverequest',
            name='cover_employee_id',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Employee who will cover during this leave period', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.employee', verbose_name='Cover Employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='cover_employee_id',
            field=models.ForeignKey(blank=True, help_text='Employee who will cover during this leave period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covering_leave_requests', to='employee.employee', verbose_name='Cover Employee'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='exclude_weekends',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30, verbose_name='Exclude Weekends'),
        ),
    ]
