# Generated by Django 4.2.23 on 2026-03-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_historicalleaverequest_cover_employee_id_and_more'),
        ('leave', '0003_leavetype_monthly_recurring'),
    ]

    operations = [
    ]
