# Generated by Django 4.2.23 on 2026-04-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_remove_leaveplan_modified_at_leaveplan_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveplan',
            name='leave_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_leave_plan', to='leave.leaverequest', verbose_name='Generated Leave Request'),
        ),
    ]
