# Generated by Django 4.2.23 on 2026-04-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_leaveplan_add_leave_request_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='prorate_on_confirmation',
            field=models.BooleanField(default=False, help_text="If enabled, leave days are pro-rated based on the employee's confirmation date in the year of assignment. Employees confirmed in a prior year receive full days.", verbose_name='Pro-rate on Confirmation'),
        ),
    ]
