# Generated by Django 4.2.23 on 2026-03-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebankdetails',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
