# Generated by Django 4.2.23 on 2026-03-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_bank_bankbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebankdetails',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Select bank from registry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_bank_details', to='employee.bank', verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='bank_branch',
            field=models.ForeignKey(blank=True, help_text='Select branch from registry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_bank_details', to='employee.bankbranch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='any_other_code1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Code #1'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Branch (Legacy)'),
        ),
    ]
