# Generated by Django 4.2.23 on 2026-04-01 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import horilla.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0004_add_bank_branch_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('job_title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], max_length=20, verbose_name='Employment Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('reason_for_leaving', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reason for Leaving')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=horilla.models.upload_path, verbose_name='Attachment')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Employee Work Experience',
                'verbose_name_plural': 'Employee Work Experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducationalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('qualification_name', models.CharField(max_length=200, verbose_name='Qualification Name')),
                ('institute_university', models.CharField(max_length=200, verbose_name='Institute / University')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('start_year', models.IntegerField(verbose_name='Start Year')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='End Year')),
                ('result_grade_gpa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Result / Grade / GPA')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('discontinued', 'Discontinued')], default='completed', max_length=20, verbose_name='Status')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=horilla.models.upload_path, verbose_name='Attachment')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_qualifications', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Employee Educational Qualification',
                'verbose_name_plural': 'Employee Educational Qualifications',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20, verbose_name='Relationship')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('identity_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Identity Number / Passport No')),
                ('insurance_covered', models.BooleanField(default=False, verbose_name='Insurance Covered')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=horilla.models.upload_path, verbose_name='Attachment')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Employee Dependent',
                'verbose_name_plural': 'Employee Dependents',
            },
        ),
    ]
