# Generated by Django 4.2.23 on 2026-04-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeeworkexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkinformation',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Confirmation Date'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Confirmation Date'),
        ),
    ]
