# Generated by Django 4.2.23 on 2026-04-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_add_confirmation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkinformation',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, help_text='Allow this employee to use WhatsApp for leave requests.', verbose_name='WhatsApp HR Enabled'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, help_text='Allow this employee to use WhatsApp for leave requests.', verbose_name='WhatsApp HR Enabled'),
        ),
    ]
