# Generated by Django 4.2.23 on 2026-03-23 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
        ('base', '0002_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('run_name', models.CharField(help_text="Name for this payroll run (e.g., 'February 2024 - Regular')", max_length=255, verbose_name='Run Name')),
                ('run_code', models.CharField(help_text='Unique code for this run (auto-generated)', max_length=50, unique=True, verbose_name='Run Code')),
                ('run_type', models.CharField(choices=[('regular', 'Regular Salary'), ('advance', 'Advance Payment'), ('bonus', 'Bonus/Incentive'), ('correction', 'Correction/Adjustment')], default='regular', max_length=20, verbose_name='Run Type')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('semi_monthly', 'Semi-Monthly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('adhoc', 'Ad-hoc')], default='monthly', max_length=20, verbose_name='Frequency')),
                ('period_start', models.DateField(verbose_name='Period Start Date')),
                ('period_end', models.DateField(verbose_name='Period End Date')),
                ('payment_date', models.DateField(help_text='Date when payment will be made', verbose_name='Payment Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('review', 'Under Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('total_employees', models.IntegerField(default=0, verbose_name='Total Employees')),
                ('total_gross', models.FloatField(default=0, verbose_name='Total Gross Pay')),
                ('total_deductions', models.FloatField(default=0, verbose_name='Total Deductions')),
                ('total_net', models.FloatField(default=0, verbose_name='Total Net Pay')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to='employee.employee', verbose_name='Approved By')),
                ('company_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('run_created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payroll_runs', to='employee.employee', verbose_name='Run Created By')),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='historicalpayslip',
            name='payroll_run',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The payroll run this payslip belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.payrollrun', verbose_name='Payroll Run'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll_run',
            field=models.ForeignKey(blank=True, help_text='The payroll run this payslip belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollrun', verbose_name='Payroll Run'),
        ),
    ]
