# Generated by Django 4.2.23 on 2026-02-24 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('name', models.CharField(help_text='Name for this conditional formatting rule', max_length=100, verbose_name='Name')),
                ('module_type', models.CharField(choices=[('payroll', 'Payroll (Earnings & Deductions)'), ('leave', 'Leave')], help_text='Which module this formatting applies to', max_length=50, verbose_name='Module Type')),
                ('use_python_code', models.BooleanField(default=False, verbose_name='Use Python Code')),
                ('python_code', models.TextField(blank=True, help_text='Custom Python code for conditions and calculations', null=True, verbose_name='Python Code')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('company_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Conditional Formatting',
                'verbose_name_plural': 'Conditional Formatting Rules',
                'ordering': ['-id'],
            },
        ),
    ]
