# Generated by Django 4.2.23 on 2026-02-25 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_conditionalformatting'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='conditional_formatting_rule',
            field=models.ForeignKey(blank=True, help_text='Select a conditional formatting rule to apply', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowances', to='payroll.conditionalformatting', verbose_name='Conditional Formatting Rule'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='use_conditional_formatting',
            field=models.BooleanField(default=False, help_text='Apply a pre-defined conditional formatting rule to this allowance', verbose_name='Use Conditional Formatting'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='conditional_formatting_rule',
            field=models.ForeignKey(blank=True, help_text='Select a conditional formatting rule to apply', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductions', to='payroll.conditionalformatting', verbose_name='Conditional Formatting Rule'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='use_conditional_formatting',
            field=models.BooleanField(default=False, help_text='Apply a pre-defined conditional formatting rule to this deduction', verbose_name='Use Conditional Formatting'),
        ),
    ]
