# Generated by Django 4.2.23 on 2026-02-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_allowance_conditional_formatting_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionalformatting',
            name='module_type',
            field=models.CharField(choices=[('payroll_earnings', 'Payroll (Earnings)'), ('payroll_deductions', 'Payroll (Deductions)'), ('leave', 'Leave')], help_text='Which module this formatting applies to', max_length=50, verbose_name='Module Type'),
        ),
    ]
