# Generated by Django 4.2.23 on 2026-03-11 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0005_payrollrun_payslip_payroll_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayslip',
            name='payroll_run',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The payroll run this payslip belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.payrollrun', verbose_name='Payroll Run'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
    ]
