# Generated by Django 4.2.23 on 2026-03-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_add_bank_branch_fk'),
        ('payroll', '0006_historicalpayslip_payroll_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='employees',
            field=models.ManyToManyField(blank=True, help_text='Employees included in this payroll run', related_name='payroll_runs', to='employee.employee', verbose_name='Employees'),
        ),
    ]
