# Generated by Django 4.2.23 on 2026-03-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payrollrun_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrun',
            name='employees',
        ),
    ]
