# Generated by Django 4.2.23 on 2026-03-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollrun_historicalpayslip_payroll_run_and_more'),
        ('payroll', '0008_add_payroll_run_employee_selection'),
    ]

    operations = [
    ]
