# Generated by Django 4.2.23 on 2026-04-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='E.164 format, e.g. +94771234567', max_length=30, unique=True, verbose_name='Phone Number')),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('MENU', 'Menu'), ('LEAVE_TYPE', 'Choosing Leave Type'), ('MONTH', 'Choosing Month'), ('DATES', 'Entering Dates'), ('CONFIRM', 'Confirming'), ('BALANCE', 'Viewing Balance')], default='IDLE', max_length=20, verbose_name='Conversation State')),
                ('session_data', models.JSONField(blank=True, default=dict)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Session',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch for WhatsApp leave requests.', verbose_name='Enable WhatsApp Integration')),
            ],
            options={
                'verbose_name': 'WhatsApp Settings',
            },
        ),
    ]
