# Generated by Django 4.2.23 on 2026-04-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecords',
            name='work_record_type',
            field=models.CharField(choices=[('FDP', 'Present'), ('HDP', 'Half Day Present'), ('ABS', 'Absent'), ('HD', 'Holiday/Company Leave'), ('CONF', 'Conflict'), ('DFT', 'Draft'), ('WFH', 'Work From Home')], max_length=10, null=True),
        ),
    ]
